FROM --platform=linux/x86_64 golang:1.18 AS builder

RUN mkdir /go/src/work

WORKDIR /go/src/work

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build main.go

FROM --platform=linux/x86_64 alpine:latest

COPY --from=builder /go/src/work/main ./